spring:
    datasource:
        url: jdbc:h2:mem:mydb
        username: sa
        password: password
        driverClassName: org.h2.Driver

    activemq:
        broker-url: tcp://localhost:61616
        user: admin
        password: admin

inspector:
    ingestion-key: {INGESTION_KEY: 69597a87ae16c25741ab1623c1b6be2e6b113ac8}
    enabled: {ENABLED: true}
    url: {URL: http://localhost:8080}
    version: {VERSION: 1.0.0}
    max-items: {MAX_ITEMS: 1000}
