spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        session_factory:
          statement_inspector: dev.inspector.spring.interceptors.repository.HibernateInterceptor

inspector:
  ingestion-key: ${INGESTION_KEY:69597a87ae16c25741ab1623c1b6be2e6b113ac8}
  enabled: ${ENABLED:true}
  url: ${URL:https://ingest.inspector.dev}
  version: ${VERSION:1.0.0}
  max-items: ${MAX_ITEMS:1000}
  max-entries: ${MAX_ENTRIES:1000}

path:
  path-list:
    - "/rest"
    - "/testing"
    - "/variable"


